ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "profession" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "interests" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "intelligence_points" INTEGER NOT NULL DEFAULT 0;
