import type { GraphEntityType } from "@/generated/prisma/client";

export const GRAPH_RELATIONSHIP_TYPES = [
  "USER_HAS_SKILL",
  "USER_HAS_EXPERTISE",
  "USER_INTERESTED_IN",
  "USER_WORKED_AT",
  "USER_CREATED_PROJECT",
  "USER_USES_TECHNOLOGY",
  "USER_USES_TOOL",
  "USER_WORKS_IN_INDUSTRY",
  "USER_TEACHES",
  "USER_MENTORS",
  "USER_ANSWERED",
  "USER_PUBLISHED",
  "PROJECT_USES_TECHNOLOGY",
  "PROJECT_HAS_SKILL",
  "PROJECT_BELONGS_TO_INDUSTRY",
  "ARTICLE_ABOUT_TOPIC",
  "COURSE_TEACHES_SKILL",
  "QUESTION_ABOUT_TOPIC",
  "QUESTION_ANSWERED_BY",
  "SKILL_RELATED_TO_SKILL",
  "TOPIC_RELATED_TO_TOPIC",
  "TECHNOLOGY_RELATED_TO_TECHNOLOGY",
] as const;

export type GraphRelationshipTypeCode =
  (typeof GRAPH_RELATIONSHIP_TYPES)[number];

export const GRAPH_ENTITY_TYPES: GraphEntityType[] = [
  "PERSON",
  "SKILL",
  "TOPIC",
  "TECHNOLOGY",
  "TOOL",
  "INDUSTRY",
  "COMPANY",
  "PROJECT",
  "PROFESSION",
  "EDUCATION",
  "CERTIFICATION",
  "ARTICLE",
  "DOCUMENT",
  "COURSE",
  "QUESTION",
  "ANSWER",
  "SERVICE",
  "PRODUCT",
  "COMMUNITY",
  "USER",
];

export const AI_GRAPH_CONFIDENCE_PUBLIC_THRESHOLD = 0.65;
